application: powerflowcal
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /m/css/
  static_dir: pages/m/css/
- url: /about/
  static_files: pages/about.html
  upload: pages/about\.html
- url: /m/about/
  static_files: pages/m/about.html
  upload: pages/m/about\.html
- url: /.*
  script: main.app

libraries:
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
