application: powerflowcal
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /m/css/
  static_dir: pages/m/css/
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /.*
  script: main.app

libraries:
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
